### ISSUE TITLE
AndroidX issues

### ISSUE THREAD

**Issue by djohannot** [benjaken/flutter_vant_kit#8]
Hi,
It is not possible at the moment to run your example. The following message occures:
`AndroidX incompatibilities may have caused this build to fail. Please migrate your app to AndroidX. See https://goo.gl/CP92wY.`

'Execution failed for task :app:preDebugBuild.                         
> Android dependency androidx.coordinatorlayout:coordinatorlayout has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution'

And even if I try to fix it, there is always another androidX dependency that fails... :(

**Comment by benjaken** [comment]
You can try [this](https://github.com/flutter/flutter/issues/27254#issuecomment-468526704) to update your gradle. I try it on my Windows 10 and it's work.
